namespace KarateSchoolSystem;

/// <summary>Represents a report generated by an administrator.</summary>
public sealed class Report : IReportable
{
    public int ReportId { get; }
    public string ReportType { get; }
    public DateTime GeneratedDate { get; }
    public Administrator GeneratedBy { get; }

    public Report(int reportId, string reportType, Administrator generatedBy)
    {
        Validation.RequirePositive(reportId, nameof(reportId));
        ReportId = reportId;
        ReportType = Validation.RequireText(reportType, nameof(reportType));
        GeneratedBy = generatedBy ?? throw new ArgumentNullException(nameof(generatedBy));
        GeneratedDate = DateTime.Now;
    }

    public string GenerateSummary() => $"{ReportType} report generated by {GeneratedBy.FirstName} {GeneratedBy.LastName}.";

    public override string ToString() => GenerateSummary();
}
